"""reset password tracker

Revision ID: 01ad298685e9
Revises: 0643d0a57312
Create Date: 2025-09-05 11:53:34.990698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ad298685e9'
down_revision = '0643d0a57312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_code', sa.String(), nullable=True))

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bvn', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('country_code', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('bank_code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('document_type', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['bvn'])
        batch_op.create_unique_constraint(None, ['account_number'])
        batch_op.drop_column('account_first_name')
        batch_op.drop_column('account_last_name')
        batch_op.drop_column('bank_swift')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_code')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_swift', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('document_type')
        batch_op.drop_column('currency')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_code')
        batch_op.drop_column('country_code')
        batch_op.drop_column('bvn')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('password_reset_code')

    # ### end Alembic commands ###
