"""feat: add charge colum local transfer

Revision ID: 0214236f3a7f
Revises: 862116e6b3a4
Create Date: 2025-12-02 20:44:31.820331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0214236f3a7f'
down_revision = '862116e6b3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_amount', sa.Float(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.drop_column('charge_amount')

    # ### end Alembic commands ###
