"""add_added email_verified_column_to_admins

Revision ID: 026c9e8ed9d6
Revises: 21e9a8a7b282
Create Date: 2024-11-08 11:50:31.620282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026c9e8ed9d6'
down_revision = '21e9a8a7b282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
