"""fix: account number datatype limitation

Revision ID: 05e50729bd06
Revises: 1b68eba5dfb2
Create Date: 2024-10-26 09:13:08.948108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e50729bd06'
down_revision = '1b68eba5dfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.alter_column('account',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
