"""fix: misspelt curreny

Revision ID: 0643d0a57312
Revises: d78eaca0c0c4
Create Date: 2025-08-16 16:04:28.386659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0643d0a57312'
down_revision = 'd78eaca0c0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_to_target_currency', sa.Text(), nullable=False, server_default='10'))
        batch_op.drop_column('amount_to_target_currenct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_to_target_currenct', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('amount_to_target_currency')

    # ### end Alembic commands ###
