"""add account_number, bank_name, external_reference, flutterwave_account_id to wallets

Revision ID: 0be891a8b1b3
Revises: 2129b3c36f79
Create Date: 2026-07-14 21:21:56.382708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be891a8b1b3'
down_revision = '2129b3c36f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('flutterwave_account_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('flutterwave_account_id')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
