"""feat: account active

Revision ID: 10e1a291f36e
Revises: f209756c44fb
Create Date: 2025-08-03 04:30:56.945812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e1a291f36e'
down_revision = 'f209756c44fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_active')

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
