"""fix: made reference numbers unique

Revision ID: 1b68eba5dfb2
Revises: d890da1f2df0
Create Date: 2024-10-26 07:50:04.373734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b68eba5dfb2'
down_revision = 'd890da1f2df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['reference'])

    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
