"""refac: accounts details

Revision ID: 2129b3c36f79
Revises: 3546d504ff19
Create Date: 2026-07-13 11:30:53.810075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2129b3c36f79'
down_revision = '3546d504ff19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('virtual_account_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['virtual_account_id'])

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_wallets_external_reference'), type_='unique')
        batch_op.drop_constraint(batch_op.f('wallets_account_number_key'), type_='unique')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('validity_type')
        batch_op.drop_column('external_reference')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(), server_default=sa.text("'individual'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('external_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('validity_type', sa.VARCHAR(), server_default=sa.text("'permanent'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('wallets_account_number_key'), ['account_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_wallets_external_reference'), ['external_reference'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('virtual_account_id')

    # ### end Alembic commands ###
