"""add unique constraint on transactions.flw_ref for webhook idempotency

Revision ID: 232def76afd1
Revises: ce013ef17e3e
Create Date: 2026-07-17 05:57:14.447430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232def76afd1'
down_revision = 'ce013ef17e3e'
branch_labels = None
depends_on = None


def upgrade():
    # Production's history was recorded as main's 0be891a8b1b3, so this may
    # already be in place there. Only add it when nothing enforces it yet.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    already_unique = any(
        c['column_names'] == ['flw_ref']
        for c in inspector.get_unique_constraints('transactions')
    ) or any(
        i['column_names'] == ['flw_ref'] and i.get('unique')
        for i in inspector.get_indexes('transactions')
    )

    if already_unique:
        return

    duplicates = bind.execute(sa.text(
        'SELECT flw_ref FROM transactions WHERE flw_ref IS NOT NULL '
        'GROUP BY flw_ref HAVING COUNT(*) > 1 LIMIT 5')).fetchall()

    if duplicates:
        # Failing here would stop the app from starting at all. Leave the
        # data alone, and say so loudly: the duplicates need a person.
        print('[migration 232def76afd1] NOT adding the unique constraint on '
              'transactions.flw_ref: these references already appear more '
              f'than once: {[row[0] for row in duplicates]}')
        return

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['flw_ref'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
