"""add unique constraint on transactions.flw_ref for webhook idempotency

Revision ID: 232def76afd1
Revises: ce013ef17e3e
Create Date: 2026-07-17 05:57:14.447430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232def76afd1'
down_revision = 'ce013ef17e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['flw_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
