"""feat: referral

Revision ID: 282b875b7d38
Revises: 712233ef5203
Create Date: 2025-08-15 05:52:11.047240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b875b7d38'
down_revision = '712233ef5203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referred_id', sa.String(), nullable=False),
    sa.Column('referred_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_code', sa.String(), nullable=False, server_default='PfirVVXzpc3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_code')

    op.drop_table('referrals')
    # ### end Alembic commands ###
