"""fix: change exchange rate datatype

Revision ID: 2cce4fc5f2ef
Revises: dca4ffb19d6f
Create Date: 2024-10-24 17:48:24.331831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cce4fc5f2ef'
down_revision = 'dca4ffb19d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
