"""feat: inbound transfer

Revision ID: 3546d504ff19
Revises: 781c9c5ad23b
Create Date: 2025-12-18 10:44:05.878253

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3546d504ff19'
down_revision = '781c9c5ad23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_transfers',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('amount', sa.Text(), nullable=False),
                    sa.Column('charge_amount', sa.Float(), nullable=False),
                    sa.Column('sender_name', sa.String(), nullable=False),
                    sa.Column('sender_bank', sa.String(), nullable=False),
                    sa.Column('sender_account_number', sa.BigInteger(), nullable=False),
                    sa.Column('narration', sa.String(), nullable=True),
                    sa.Column('recipient_name', sa.String(), nullable=False),
                    sa.Column('recipient_bank', sa.String(), nullable=False),
                    sa.Column('recipient_account_number', sa.BigInteger(), nullable=False),
                    sa.Column('reference_number', sa.String(), nullable=False),
                    sa.Column('session_id', sa.String(), nullable=False),
                    sa.Column('stamp_duty', sa.Float(), nullable=False),
                    sa.Column('transfer_type', sa.String(), nullable=False),
                    sa.Column('transfer_pair', sa.String(), nullable=False),
                    sa.Column('transaction_status', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('wallet_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('session_id')
                    )
    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_amount', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('sender_account_number', sa.BigInteger(), nullable=False, server_default=sa.text(
            "(floor(random() * 9000000000) + 1000000000)::bigint"
        )))
        batch_op.add_column(sa.Column('session_id',
                                      sa.String(),
                                      nullable=False,
                                      server_default=sa.text("gen_random_uuid()::text")))
        batch_op.add_column(sa.Column('stamp_duty', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.create_unique_constraint(None, ['session_id'])

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_account_number', sa.BigInteger(), nullable=False, server_default=sa.text(
            "(floor(random() * 9000000000) + 1000000000)::bigint"
        )))
        batch_op.add_column(sa.Column('session_id',
                                      sa.String(),
                                      nullable=False,
                                      server_default=sa.text("gen_random_uuid()::text")))
        batch_op.add_column(sa.Column('stamp_duty', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.create_unique_constraint(None, ['session_id'])

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_amount', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('sender_account_number', sa.BigInteger(), nullable=False, server_default=sa.text(
            "(floor(random() * 9000000000) + 1000000000)::bigint"
        )))
        batch_op.add_column(sa.Column('session_id',
                                      sa.String(),
                                      nullable=False,
                                      server_default=sa.text("gen_random_uuid()::text")))
        batch_op.add_column(sa.Column('stamp_duty', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.create_unique_constraint(None, ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stamp_duty')
        batch_op.drop_column('session_id')
        batch_op.drop_column('sender_account_number')
        batch_op.drop_column('charge_amount')

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stamp_duty')
        batch_op.drop_column('session_id')
        batch_op.drop_column('sender_account_number')

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stamp_duty')
        batch_op.drop_column('session_id')
        batch_op.drop_column('sender_account_number')
        batch_op.drop_column('charge_amount')

    op.drop_table('inbound_transfers')
    # ### end Alembic commands ###
