"""refac: foreign transfer model

Revision ID: 375ab40cca73
Revises: 3cd8f0ac710a
Create Date: 2025-11-14 17:45:19.956338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '375ab40cca73'
down_revision = '3cd8f0ac710a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recipient_account_number', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('transfer_pair', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transaction_status', sa.String(), nullable=False))
        batch_op.drop_column('amount_from_sender')
        batch_op.drop_column('account_number')
        batch_op.drop_column('wallet_identifier')
        batch_op.drop_column('amount_to_recipient')

    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_bank_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_expiration_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('customer_code', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['reference'])
        batch_op.drop_column('flw_ref')
        batch_op.drop_column('amount')
        batch_op.drop_column('frequency')
        batch_op.drop_column('order_ref')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('created_at_by_flw')
        batch_op.drop_column('response_message')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('note')
        batch_op.drop_column('response_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_code', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('response_message', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at_by_flw', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('order_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('flw_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('customer_code')
        batch_op.drop_column('account_expiration_datetime')
        batch_op.drop_column('status')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_bank_name')
        batch_op.drop_column('reference')

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_to_recipient', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wallet_identifier', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_from_sender', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('transaction_status')
        batch_op.drop_column('transfer_pair')
        batch_op.drop_column('recipient_account_number')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
