"""feat: virtual ngn account

Revision ID: 3aa419df1828
Revises: fd7bc931f4e7
Create Date: 2025-09-09 20:37:08.045718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa419df1828'
down_revision = 'fd7bc931f4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_account_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response_code', sa.String(), nullable=False),
    sa.Column('response_message', sa.String(), nullable=False),
    sa.Column('flw_ref', sa.String(), nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('created_at_by_flw', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_ticker', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=False, server_default='00000000000'))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=False, server_default='payverve bank'))
        batch_op.add_column(sa.Column('currency_ticker', sa.String(), nullable=False, server_default='ngn'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('currency_ticker')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')

    op.drop_table('virtual_account_numbers')
    # ### end Alembic commands ###
