"""feat: transactions

Revision ID: 469560209da9
Revises: 4624d3cdda92
Create Date: 2025-09-23 21:20:13.868787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469560209da9'
down_revision = '4624d3cdda92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_ref', sa.String(), nullable=False),
    sa.Column('flw_ref', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
