"""refac: models foreign keys

Revision ID: 4b30b50419a6
Revises: f2527bdcf858
Create Date: 2025-08-03 00:20:39.273610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b30b50419a6'
down_revision = 'f2527bdcf858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('admins_admin_role_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_roles', ['admin_role_id'], ['id'])
        batch_op.drop_column('admin_role')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('currency_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('bank_accounts_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('bank_accounts_currency_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('currency')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('beneficiaries_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('foreign_transfers_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('foreign_transfers_wallet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('wallet')

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('local_transfers_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('local_transfers_wallet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('wallet')

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('payverve_transfers_wallet_fkey', type_='foreignkey')
        batch_op.drop_constraint('payverve_transfers_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('wallet')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('currency_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('wallets_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('wallets_currency_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wallets_currency_fkey', 'currencies', ['currency'], ['id'])
        batch_op.create_foreign_key('wallets_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('currency_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payverve_transfers_user_fkey', 'users', ['user'], ['id'])
        batch_op.create_foreign_key('payverve_transfers_wallet_fkey', 'wallets', ['wallet'], ['id'])
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('local_transfers_wallet_fkey', 'wallets', ['wallet'], ['id'])
        batch_op.create_foreign_key('local_transfers_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('foreign_transfers_wallet_fkey', 'wallets', ['wallet'], ['id'])
        batch_op.create_foreign_key('foreign_transfers_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('beneficiaries_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bank_accounts_currency_fkey', 'currencies', ['currency'], ['id'])
        batch_op.create_foreign_key('bank_accounts_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('currency_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admins_admin_role_fkey', 'admin_roles', ['admin_role'], ['id'])
        batch_op.drop_column('admin_role_id')

    # ### end Alembic commands ###
