"""feat: adjusted columns for VA

Revision ID: 4ba1db8e4389
Revises: af4a2a919ad9
Create Date: 2025-12-02 18:47:26.899756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba1db8e4389'
down_revision = 'af4a2a919ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Fill existing NULL values with default first
    op.execute("UPDATE users SET gender = 'male' WHERE gender IS NULL")
    op.execute("UPDATE users SET date_of_birth = '2000-01-01' WHERE date_of_birth IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False, server_default='male')
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False, server_default=sa.text("'2000-01-01'"))

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        # Step 1: Add as nullable
        batch_op.add_column(sa.Column('externalReference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(), nullable=False, server_default='individual'))
        batch_op.add_column(sa.Column('validityType', sa.String(), nullable=False, server_default='permanent'))

    # Step 2: Populate existing rows with unique values
    op.execute("""
        UPDATE wallets
        SET "externalReference" = 'ext-ref-' || substr(md5(random()::text), 1, 10)
        WHERE "externalReference" IS NULL
    """)

    # Step 3: Make NOT NULL and add unique constraint
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('externalReference', nullable=False)
        batch_op.create_unique_constraint(None, ['externalReference'])

    # Step 4 (optional): Set server default for future inserts
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('externalReference', server_default=sa.text("'ext-ref-default'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('validityType')
        batch_op.drop_column('externalReference')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
