"""feat: jti

Revision ID: 4eb07be8f676
Revises: 6f487b37d99f
Create Date: 2025-10-07 19:22:17.005611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb07be8f676'
down_revision = '6f487b37d99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jti')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('account_active')

    # ### end Alembic commands ###
