"""feat: added reference number to local transfer

Revision ID: 556cbdaf72bb
Revises: 05e50729bd06
Create Date: 2024-10-30 02:01:32.423595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556cbdaf72bb'
down_revision = '05e50729bd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('where', sa.String(), nullable=False))

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rference_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transfer_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.drop_column('transfer_type')
        batch_op.drop_column('rference_number')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('where')

    # ### end Alembic commands ###
