"""db re-initialisation

Revision ID: 6e58472813dc
Revises: 
Create Date: 2025-10-26 12:40:00.657609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e58472813dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payverve_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referred_id', sa.String(), nullable=False),
    sa.Column('referred_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('channel_contact', sa.String(), nullable=False),
    sa.Column('code_sent', sa.Text(), nullable=False),
    sa.Column('expiration_time', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('auth_pin', sa.String(), nullable=True),
    sa.Column('transaction_pin', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('account_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=False),
    sa.Column('password_reset_code', sa.String(), nullable=True),
    sa.Column('jti', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('account_active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('password_reset_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('admin_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_role_id'], ['admin_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bvn', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_code', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('bvn')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('where', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kycs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('bvn', sa.String(), nullable=True),
    sa.Column('nin', sa.String(), nullable=True),
    sa.Column('bvn_present', sa.Boolean(), nullable=False),
    sa.Column('nin_present', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bvn'),
    sa.UniqueConstraint('nin')
    )
    op.create_table('spend_saves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Text(), nullable=False),
    sa.Column('percentage_to_save', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_ref', sa.String(), nullable=True),
    sa.Column('flw_ref', sa.String(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_account_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response_code', sa.String(), nullable=False),
    sa.Column('response_message', sa.String(), nullable=False),
    sa.Column('flw_ref', sa.String(), nullable=False),
    sa.Column('order_ref', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('created_at_by_flw', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_ticker', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund', sa.Text(), nullable=False),
    sa.Column('wallet_identifier', sa.BigInteger(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('currency_ticker', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('wallet_identifier')
    )
    op.create_table('foreign_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_from_sender', sa.Text(), nullable=False),
    sa.Column('amount_to_recipient', sa.Text(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('sender_bank', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('wallet_identifier', sa.BigInteger(), nullable=False),
    sa.Column('swift_code', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_bank', sa.String(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_from_sender', sa.Text(), nullable=False),
    sa.Column('amount_to_recipient', sa.Text(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('sender_bank', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('wallet_identifier', sa.BigInteger(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_bank', sa.String(), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payverve_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_from_sender', sa.Text(), nullable=False),
    sa.Column('amount_to_recipient', sa.Text(), nullable=False),
    sa.Column('coversion_rate', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('wallet_identifier', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transfer_pair', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('swap_currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount_from_base_currency', sa.Text(), nullable=False),
    sa.Column('amount_to_target_currency', sa.Text(), nullable=False),
    sa.Column('coversion_rate', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=True),
    sa.Column('wallet_identifier', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('swap_pairs', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_currencies')
    op.drop_table('payverve_transfers')
    op.drop_table('local_transfers')
    op.drop_table('foreign_transfers')
    op.drop_table('wallets')
    op.drop_table('virtual_account_numbers')
    op.drop_table('transactions')
    op.drop_table('spend_saves')
    op.drop_table('kycs')
    op.drop_table('beneficiaries')
    op.drop_table('bank_accounts')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('token_verifications')
    op.drop_table('referrals')
    op.drop_table('payverve_wallets')
    op.drop_table('exchange_rates')
    op.drop_table('currencies')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
