"""feat: spend & save

Revision ID: 6f487b37d99f
Revises: 03d19e16bace
Create Date: 2025-09-24 00:06:51.074626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f487b37d99f'
down_revision = '03d19e16bace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_saves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Text(), nullable=False),
    sa.Column('percentage_to_save', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))
        batch_op.alter_column('tx_ref',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('flw_ref',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('flw_ref',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('tx_ref',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('note')

    op.drop_table('spend_saves')
    # ### end Alembic commands ###
