"""refac: local and intl transfer

Revision ID: 712233ef5203
Revises: d71643e62a06
Create Date: 2025-08-03 22:18:51.808941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712233ef5203'
down_revision = 'd71643e62a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_from_sender', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('amount_to_recipient', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sender_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sender_bank', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('wallet_identifier', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('recipient_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('recipient_bank', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('reference_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transfer_type', sa.String(), nullable=False))
        batch_op.drop_column('bank')
        batch_op.drop_column('account')
        batch_op.drop_column('name')
        batch_op.drop_column('amount')
        batch_op.drop_column('country')

    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_from_sender', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('amount_to_recipient', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sender_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sender_bank', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('wallet_identifier', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('recipient_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('recipient_bank', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('reference_number', sa.String(), nullable=False))
        batch_op.drop_column('bank')
        batch_op.drop_column('account')
        batch_op.drop_column('rference_number')
        batch_op.drop_column('name')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rference_number', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('reference_number')
        batch_op.drop_column('account_number')
        batch_op.drop_column('recipient_bank')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('wallet_identifier')
        batch_op.drop_column('sender_bank')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('amount_to_recipient')
        batch_op.drop_column('amount_from_sender')

    with op.batch_alter_table('foreign_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('transfer_type')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('account_number')
        batch_op.drop_column('recipient_bank')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('wallet_identifier')
        batch_op.drop_column('sender_bank')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('amount_to_recipient')
        batch_op.drop_column('amount_from_sender')

    # ### end Alembic commands ###
