"""feat: address to kyc

Revision ID: 781c9c5ad23b
Revises: 0214236f3a7f
Create Date: 2025-12-05 10:07:13.549015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781c9c5ad23b'
down_revision = '0214236f3a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kycs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('house_number')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('street_name')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('house_number', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('kycs', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
