"""fix: changed received amount datatype to float, swap currency

Revision ID: 82453d71c5db
Revises: 2cce4fc5f2ef
Create Date: 2024-10-24 20:05:23.187670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82453d71c5db'
down_revision = '2cce4fc5f2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.alter_column('amount_received',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='amount_received::float')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.alter_column('amount_received',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
