"""fix: name of columns for VA

Revision ID: 862116e6b3a4
Revises: 4ba1db8e4389
Create Date: 2025-12-02 19:41:22.341199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862116e6b3a4'
down_revision = '4ba1db8e4389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('external_reference', sa.String(), nullable=False, server_default='ext-ref-default'))
        batch_op.add_column(sa.Column('external_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('validity_type', sa.String(), nullable=False, server_default='permanent'))

    op.execute("""
        UPDATE wallets
        SET external_reference = CONCAT('ext-', id)
        WHERE external_reference IS NULL
    """)

    with op.batch_alter_table('wallets') as batch_op:
        batch_op.alter_column('external_reference', nullable=False)
        batch_op.drop_constraint(batch_op.f('wallets_externalReference_key'), type_='unique')
        batch_op.create_unique_constraint('uq_wallets_external_reference', ['external_reference'])
        # batch_op.create_unique_constraint(None, ['external_reference'])
        batch_op.drop_column('validityType')
        batch_op.drop_column('externalReference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalReference', sa.VARCHAR(), server_default=sa.text("'ext-ref-default'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('validityType', sa.VARCHAR(), server_default=sa.text("'permanent'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('wallets_externalReference_key'), ['externalReference'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('validity_type')
        batch_op.drop_column('external_reference')

    # ### end Alembic commands ###
