"""feat: made moil number nullable

Revision ID: 88b4864772a9
Revises: 282b875b7d38
Create Date: 2025-08-16 14:48:19.480605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b4864772a9'
down_revision = '282b875b7d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
