"""refac: include currenct ticker field in transaction

Revision ID: a23896bca01b
Revises: a9379b2cedb4
Create Date: 2025-11-15 08:50:39.498181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23896bca01b'
down_revision = 'a9379b2cedb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_ticker', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('currency_ticker')

    # ### end Alembic commands ###
