"""refac: include new field in transaction

Revision ID: a9379b2cedb4
Revises: 375ab40cca73
Create Date: 2025-11-15 07:36:54.239424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9379b2cedb4'
down_revision = '375ab40cca73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transaction_flow', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transaction_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_title')
        batch_op.drop_column('transaction_flow')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
