"""feat: kyc new column

Revision ID: af4a2a919ad9
Revises: 22f7a10cf6b0
Create Date: 2025-11-24 23:57:16.050509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4a2a919ad9'
down_revision = '22f7a10cf6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kycs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie', sa.String(), nullable=True, server_default='https://default.selfie.url/image.png'))
        batch_op.add_column(sa.Column('full_name_present', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('selfie_present', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('phone_number_present', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('address_present', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kycs', schema=None) as batch_op:
        batch_op.drop_column('address_present')
        batch_op.drop_column('phone_number_present')
        batch_op.drop_column('selfie_present')
        batch_op.drop_column('full_name_present')
        batch_op.drop_column('selfie')

    # ### end Alembic commands ###
