"""fix: change virtual_account_numbers.account_number from BigInteger to String to preserve leading zeros

Revision ID: ce013ef17e3e
Revises: 2129b3c36f79
Create Date: 2026-07-15 20:31:46.513281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce013ef17e3e'
down_revision = '2129b3c36f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.BIGINT(),
                              type_=sa.String(),
                              existing_nullable=False,
                              postgresql_using='account_number::varchar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.String(),
                              type_=sa.BIGINT(),
                              existing_nullable=False,
                              postgresql_using='account_number::bigint')
    # ### end Alembic commands ###
