"""feat: payverve wallet

Revision ID: d71643e62a06
Revises: 10e1a291f36e
Create Date: 2025-08-03 14:47:45.267652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71643e62a06'
down_revision = '10e1a291f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payverve_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_from_sender', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('amount_to_recipient', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('coversion_rate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('wallet_identifier', sa.BigInteger(), nullable=False))
        batch_op.drop_column('account')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('wallet_identifier')
        batch_op.drop_column('coversion_rate')
        batch_op.drop_column('amount_to_recipient')
        batch_op.drop_column('amount_from_sender')

    op.drop_table('payverve_wallets')
    # ### end Alembic commands ###
