"""refac: updated fields to suit new params

Revision ID: d78eaca0c0c4
Revises: ebb27329b58f
Create Date: 2025-08-16 15:43:16.044936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78eaca0c0c4'
down_revision = 'ebb27329b58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_from_base_currency', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('amount_to_target_currenct', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('coversion_rate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('narration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('wallet_identifier', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('swap_pairs', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('swap_currencies_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])
        batch_op.drop_column('amount_received')
        batch_op.drop_column('amount')
        batch_op.drop_column('target_currency')
        batch_op.drop_column('user')
        batch_op.drop_column('currency_pair')
        batch_op.drop_column('base_currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_currency', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency_pair', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_currency', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_received', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('swap_currencies_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('swap_pairs')
        batch_op.drop_column('wallet_identifier')
        batch_op.drop_column('narration')
        batch_op.drop_column('coversion_rate')
        batch_op.drop_column('amount_to_target_currenct')
        batch_op.drop_column('amount_from_base_currency')

    # ### end Alembic commands ###
