"""feat: added new columns to payverve transfer

Revision ID: d890da1f2df0
Revises: 82453d71c5db
Create Date: 2024-10-26 07:46:45.514541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd890da1f2df0'
down_revision = '82453d71c5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transaction_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('transfer_pair', sa.String(), nullable=False))

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('payverve_transfers', schema=None) as batch_op:
        batch_op.drop_column('transfer_pair')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
