"""feat: add more details to the swap currency model

Revision ID: dca4ffb19d6f
Revises: 21e9a8a7b282
Create Date: 2024-10-24 17:21:58.994184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca4ffb19d6f'
down_revision = '21e9a8a7b282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('currency_pair', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('amount_received', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('reference', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_currencies', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('amount_received')
        batch_op.drop_column('currency_pair')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
