"""fix: datatype for ss

Revision ID: e3af41342887
Revises: 7ef364fb2e89
Create Date: 2025-11-06 22:11:44.024635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3af41342887'
down_revision = '7ef364fb2e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_saves', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_saves', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
