"""feat: token verification

Revision ID: f209756c44fb
Revises: 4b30b50419a6
Create Date: 2025-08-03 01:59:31.327335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f209756c44fb'
down_revision = '4b30b50419a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('channel_contact', sa.String(), nullable=False),
    sa.Column('code_sent', sa.Text(), nullable=False),
    sa.Column('expiration_time', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_identifier', sa.BigInteger(), nullable=False))
        batch_op.alter_column('fund',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('wallets_account_number_key', type_='unique')
        batch_op.create_unique_constraint(None, ['wallet_identifier'])
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('wallets_account_number_key', ['account_number'])
        batch_op.alter_column('fund',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('wallet_identifier')

    op.drop_table('token_verifications')
    # ### end Alembic commands ###
