"""add fcm_token to users

Revision ID: fad65255d675
Revises: 232def76afd1
Create Date: 2026-07-25 19:08:55.426651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad65255d675'
down_revision = '232def76afd1'
branch_labels = None
depends_on = None


def upgrade():
    # Production's history was recorded as main's 0be891a8b1b3 while this
    # column was already in use, so it may exist before this runs. Only add it
    # when it is missing.
    columns = [c['name'] for c in sa.inspect(op.get_bind()).get_columns('users')]

    if 'fcm_token' in columns:
        return

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
