"""feat: kyc

Revision ID: fd7bc931f4e7
Revises: 01ad298685e9
Create Date: 2025-09-05 13:13:32.811498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7bc931f4e7'
down_revision = '01ad298685e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kycs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('bvn', sa.String(), nullable=True),
    sa.Column('nin', sa.String(), nullable=True),
    sa.Column('bvn_present', sa.Boolean(), nullable=False),
    sa.Column('nin_present', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bvn'),
    sa.UniqueConstraint('nin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kycs')
    # ### end Alembic commands ###
