"""kyc, user relationship type

Revision ID: fdbb9827aa2a
Revises: 6e58472813dc
Create Date: 2025-11-05 14:33:03.197558

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fdbb9827aa2a'
down_revision = '6e58472813dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.VARCHAR(),
                              type_=sa.BigInteger(),
                              existing_nullable=False,
                              postgresql_using='account_number::bigint')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.VARCHAR(),
                              type_=sa.BigInteger(),
                              existing_nullable=False,
                              postgresql_using='account_number::bigint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.BigInteger(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    with op.batch_alter_table('virtual_account_numbers', schema=None) as batch_op:
        batch_op.alter_column('account_number',
                              existing_type=sa.BigInteger(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)

    # ### end Alembic commands ###
