# Generated by Django 4.2.6 on 2023-12-20 10:24

import core.utils.Currency
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('dollar_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('pound_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('£', 'Pound'), ('$', 'Dollar'), ('NGN', 'Naira')],
                                              default=core.utils.Currency.Currency['Naira'], max_length=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('transaction_status', models.CharField(
                    choices=[('Initiated', 'INITIATED'), ('Pending', 'PENDING'), ('Completed', 'COMPLETED')],
                    max_length=15)),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_from',
                                               to='core.account')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_to',
                                             to='core.account')),
            ],
        ),
    ]
