# Generated by Django 4.2.6 on 2023-12-23 10:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayverveUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('PayVerve', 'Payverve'), ('Other Banks', 'Other Banks')], default='PayVerve', max_length=15)),
                ('account_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('narration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransferAdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='ECO BANK', max_length=50)),
                ('country', django_countries.fields.CountryField(default='Nigeria', max_length=2)),
                ('bank_swift', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=models.SET(0), related_name='owner', to='core.payverveuser')),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='acc_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='acc_to',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet',
            field=models.ForeignKey(on_delete=models.SET(0), to='core.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(default=None, on_delete=models.SET(0), to='core.transfer'),
        ),
    ]
