# Generated by Django 4.2.6 on 2023-12-23 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_payverveuser_transfer_transferadditionalinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
