# Generated by Django 4.2.6 on 2023-12-23 10:32

import core.utils.Currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('£', 'Pound'), ('$', 'Dollar'), ('NGN', 'Naira')],
                                   default=core.utils.Currency.Currency['Naira'], max_length=20),
        ),
    ]
