# Generated by Django 4.2.6 on 2023-12-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='option',
            field=models.CharField(choices=[('PayVerve', 'Payverve'), ('Other Banks', 'Other Banks')], default='PayVerve', max_length=20),
        ),
    ]
