# Generated by Django 4.2.6 on 2023-12-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transfer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
    ]
