# Generated by Django 4.2.6 on 2023-12-24 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(default=None, on_delete=models.SET(0), related_name='transfers', to='core.transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='wallet',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='transfers', to='core.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(0), related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
