# Generated by Django 4.2.6 on 2023-12-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_transfer_alter_transfer_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(default=None, on_delete=models.SET(0), related_name='transactions', to='core.transfer'),
        ),
    ]
