# Generated by Django 4.2.6 on 2024-01-04 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_alter_transaction_transfer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payverveuser',
            managers=[
            ],
        ),
    ]
