# Generated by Django 4.2.6 on 2024-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_alter_payverveuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferadditionalinformation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
    ]
