# Generated by Django 4.2.6 on 2024-01-15 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_transferadditionalinformation_exchange_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayverveUser',
        ),
    ]
