# Generated by Django 4.2.6 on 2024-01-15 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_delete_payverveuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferadditionalinformation',
            options={'verbose_name': 'core_transfer_additional_information'},
        ),
        migrations.AlterModelTable(
            name='transferadditionalinformation',
            table='core_transfer_additional_information',
        ),
    ]
