# Generated by Django 4.2.6 on 2024-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_alter_transferadditionalinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferadditionalinformation',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='core.transfer'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
    ]
