# Generated by Django 4.2.6 on 2024-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_transferadditionalinformation_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='narration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
