# Generated by Django 4.2.6 on 2024-01-19 21:36

import core.utils.Currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transfer_created_at_transfer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='created_at',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='updated_at',
            new_name='updated_dt',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pound'), ('USD', 'Dollar'), ('NGN', 'Naira')], default=core.utils.Currency.Currency['Naira'], max_length=20),
        ),
    ]
