# Generated by Django 4.2.6 on 2024-01-20 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_currencyexchangerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchangerate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
